apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672          # Service Port
    targetPort: 5672    # Container Port